### ISSUE TITLE
[Bug] `--output json` does not output JSON sometimes

### ISSUE THREAD

**Issue by askreet** [temporalio/cli#346] opened 2023-09-29 14:35 UTC
### What are you really trying to do?

I am trying to integrate programmatically with the `temporal` cli. For example by listing schedules with `temporal schedule list --output json`.

### Describe the bug

If there are no schedules configured, the command outputs no bytes. No bytes is not valid JSON. It would be semantically correct to output `[]` in this case.

### Minimal Reproduction

1. Have a cluster with no schedules.
2. Run `temporal schedule list --output json`.
3. Attempt to parse this output with your favorite JSON library and be saddened by the result.

### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: `0.10.5 (server 1.21.4) (ui 2.17.0)`
- Are you using Docker or Kubernetes or building Temporal from source? Local install of CLI, docker container for Server.

**Comment by josh-berry** [comment] 2023-09-29 17:35
Thanks for the report; this is a duplicate of #307, so I'll close this one and make a note about `temporal schedule list` there.

**Closed by josh-berry** 2023-09-29 17:35 UTC
Labels: bug
