### ISSUE TITLE
Problem with sending Signals containing JSON as input in Temporal CLI

### ISSUE THREAD

**Issue by angelazhou32** [temporalio/cli#411] opened 2024-01-11 19:05 UTC
I am unable to send Signals containing JSON as input in the Temporal CLI. E.g.:

`temporal workflow signal --workflow-id="add-groups-workflow" --name="join" --input='{"userId": "user-1", "groupId": "group-2"}'
`
I got the error:
`Error: input is not valid JSON: unexpected end of JSON input.`
I also tried:

`temporal workflow signal --workflow-id="add-groups-workflow" --name="join" --input='\{"userId": "user-1", "groupId": "group-2"\}'`

`temporal workflow signal --workflow-id="add-groups-workflow" --name="join" --input="'{\"userId\": \"user-1\", \"groupId\": \"group-2\"}'"`

`Error: input is not valid JSON: invalid character '\\' looking for beginning of value`

And many more combinations. I did verify that they are valid JSON. I did see there was a [bug for this already filed](https://github.com/temporalio/cli/issues/159) but this was a long time ago. Perhaps this is a regression.

Note that removing the comma and doing something like `--input '{"userId": "user-1"}'` - does not error out.

**Comment by tiagojhmoreira** [comment] 2024-01-15 11:40
I also have a problem sending signals with input '--input-file'. 

My example (Using Spring with Koltin): A workflow with id 'abc' is running, and then I send a signal with input of JSON file.

Interface HandleEventWorkflow :
```
  @SignalMethod
  fun addEvent(event: Event)

  data class Event(
    val eventId: String
  )
```

Class HandleEventWorkflowImpl:
```
  override fun addEvent(event: Event) {
    logger.info("HandleEventWorkflow Log: Event received => $event")
  }
```

'dummy_input.json' file:
```
{
    "event_id": "1234"
}
```


Temporal cli command:` temporal workflow signal --input-file dummy_input.json --workflow-id abc --name addEvent --env default`
Error: `Caused By: java.lang.NullPointerException: Parameter specified as non-null is null: method ... HandleEventWorkflowImpl.addEvent, parameter event`

I downgraded the temporal version to 0.10.6, and now the workflow can receive the input successfully.

Can we consider it to be the same issue or is it better to open a new one?

**Comment by cretz** [comment] 2024-01-29 14:44
(note, this may have been fixed in the past with a library downgrade at #148 we inadvertently bumped in the interim)

**Closed** 2024-01-30 00:03 UTC
Labels: bug

**Comment by josh-berry** [comment] 2024-01-30 00:08
@tiagojhmoreira Yours seems like a different issue; can you use something like `--input "$(cat dummy_input.json)"` as a workaround for now? We are working on some large internal improvements to the CLI which I think will address this issue. (If you need us to look at it more urgently, please feel free to open another issue though!)

**Comment by josh-berry** [comment] 2024-01-30 00:09
The original issue (`--input` options not being parsed correctly) should be addressed in the next release (which is coming very soon and is not tied to the refactor I mentioned).
