### ISSUE TITLE
[Bug] Cannot execute TestWorkflowEnvironment on linux due to issue with CLI

### ISSUE THREAD

**Issue by johnmorr-citrix** [temporalio/cli#542] opened 2024-04-29 21:24 UTC
Using the @temporalio/testing library from NPM, we started having failed tests on our linux-based machines about a few hours ago. The testing library is failing to download and start the temporal server. This appears to coincide with the most recent CLI release.

### Describe the bug

When running a @temporalio/testing TestWorkflowEnvironment, we are getting errors starting:
```
   Failed to connect before the deadline
```

### Environment/Versions

Ubuntu 22.04.1 LTS

Appears to work on MacOS. 

### Additional context

We have made NO changes on our end. It worked 7 hours ago. And stopped working on all linux dev boxes after that time. The latest CLI release appears to be related.

**Comment by cretz** [comment] 2024-04-29 22:02
Can you provide the exact call to `createLocal` you are making? I wonder if it's one of the options causing this issue.

**Comment by mjameswh** [comment] 2024-05-02 14:14
We identified the root cause of this issue (see #544). Closing this ticket in favor of the other, more specific one.

**Closed by mjameswh** 2024-05-02 14:14 UTC
Labels: bug
