### ISSUE TITLE
Argument parsing issue with `temporal env set --codec-endpoint`

### ISSUE THREAD

**Issue by axfelix** [temporalio/cli#414] opened 2024-01-18 02:55 UTC
### What are you really trying to do?

Set a codec server endpoint as documented in https://docs.temporal.io/dataconversion#cli

### Describe the bug

Run `temporal env set --codec-endpoint "http://localhost:8081"`

Result:

`Error: invalid number of args, expected 2: property and value`

### Minimal Reproduction

Trying to follow the other example on that page also doesn't work:

`temporal --codec-endpoint "http://localhost:8081" --namespace "default" workflow show --workflow-id "codecserver_workflowID"  --output "table"`

`Incorrect Usage: flag provided but not defined: -codec-endpoint`

So it seems like something is wrong with how the `--codec-endpoint` flag is parsed.

### Environment/Versions

temporal version 0.10.7 (server 1.22.2) (ui 2.21.3) (x86 Mac)

**Comment by bergundy** [comment] 2024-01-18 22:56
You're not using the command correctly, the syntax is:

```
temporal env set $your_env.codec-endpoint "http://localhost:8081"
```

The help string for this command has an example so I don't think there's anything to do here. I'm closing this issue.
Please re-open if you're not satisfied with this response.

**Closed by bergundy** 2024-01-18 22:56 UTC
Labels: bug

**Comment by tomwheeler** [comment] 2024-01-18 22:57
Using the steps that @axfelix provided above, I can reproduce both problems on `temporal` version 0.10.7, running on an Apple Silicon (M2) Mac.

**Comment by tomwheeler** [comment] 2024-01-18 23:05
I posted my comment without seeing Roey's message, which reopened the issue. That was not my intent (although I admit that I don't understand Roey's comment, because running `temporal workflow show --help` shows a usage message that includes a `--codec-endpoint` option, just as Alex had specified in his command. 

Is the problem that this option is not supported and therefore the usage message should not display it?

**Comment by bergundy** [comment] 2024-01-18 23:20
That's because urfave (the cli argument parsing library we're currently using) doesn't support positional arguments at the top level.

You have to issue the command as:

```
temporalworkflow show --workflow-id "codecserver_workflowID"  --output "table"  --codec-endpoint "http://localhost:8081" --namespace "default"
```

There's a PR that's rewriting the entire CLI to use cobra and remove this restriction.
