### ISSUE TITLE
[Feature Request] signal_with_start in CLI

### ISSUE THREAD

**Issue by nishkrishnan** [temporalio/cli#353] opened 2023-10-09 21:27 UTC
### Is your feature request related to a problem? Please describe.

The cli does not contain signal-with-start which we use.  Our workaround is to just create a go cli tool that wraps the go sdk which supports this however, it would be nice to not have that.

**Comment by josh-berry** [comment] 2024-11-26 18:08
Duplicate of #332.

**Closed by josh-berry** 2024-11-26 18:08 UTC
Labels: enhancement
