### ISSUE TITLE
Apply markdown processing to --help definitions

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/cli#305] opened 2023-08-03 18:17 UTC
### Is your feature request related to a problem? Please describe.

--help Definition texts output markdown links as plain text, making them hard to read

### Describe the solution you'd like

We apply markdown to text processor for Usage texts. Make the same for Definitions https://github.com/temporalio/cli/blob/36afc181974f4a77fca287b432a457657a249bcc/helpprinter/helpprinter.go#L42C10-L42C21

**Comment by josh-berry** [comment] 2023-09-06 00:45
Duplicate of #151

**Closed by josh-berry** 2023-09-06 00:45 UTC
Labels: duplicate, enhancement
